#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of fuct. Copyright (c) 2014 Ari Karhu.
# See the LICENSE file for license rights and limitations (MIT).
#

__author__ = 'ari'

from os.path import join
from sys import path

path.append(join('src', 'main', 'python'))
from fuct.apps import loader

loader.execute()
